LOD_RESOLUTION    = '0'
LOD_GEOMETRY      = '6'
LOD_MEMORY        = '9'
LOD_VIEW_GEOMETRY = '14'
LOD_FIRE_GEOMETRY = '15'

COLLECTION_VISUALS      = "Visuals"
COLLECTION_GEOMETRIES   = "Geometries"
COLLECTION_POINT_CLOUDS = "Point Clouds"
COLLECTION_ORDER        = [COLLECTION_VISUALS, COLLECTION_GEOMETRIES, COLLECTION_POINT_CLOUDS]

GEOMETRY_LOD_VALUE = "1.000e+13"
INVVIEW_OFFSET     = 2.5

PROP_LOD_NO_SHADOW = 'lodnoshadow'
PROP_AUTOCENTER    = 'autocenter'
